# Generated by Django 5.1.5 on 2025-03-25 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_article_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="user",
        ),
    ]
