# Generated by Django 5.1.5 on 2025-04-13 23:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ongoing", "Ongoing"),
                            ("hiatus", "On Hiatus"),
                            ("completed", "Completed"),
                        ],
                        default="ongoing",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(max_length=200)),
                ("event_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("notes", models.TextField(blank=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="dnd_manager.campaign",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("player_name", models.CharField(max_length=100)),
                (
                    "class_type",
                    models.CharField(
                        choices=[
                            ("Fighter", "Fighter"),
                            ("Wizard", "Wizard"),
                            ("Rogue", "Rogue"),
                            ("Cleric", "Cleric"),
                        ],
                        default="Fighter",
                        max_length=50,
                    ),
                ),
                ("level", models.PositiveIntegerField(default=1)),
                (
                    "race",
                    models.CharField(
                        choices=[
                            ("Human", "Human"),
                            ("Elf", "Elf"),
                            ("Dwarf", "Dwarf"),
                            ("Halfling", "Halfling"),
                        ],
                        default="Human",
                        max_length=50,
                    ),
                ),
                ("backstory", models.TextField(blank=True)),
                ("character_image", models.ImageField(blank=True, upload_to="")),
                ("gold", models.PositiveIntegerField(default=0)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="characters",
                        to="dnd_manager.campaign",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NPC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("location", models.CharField(blank=True, max_length=100)),
                ("npc_image", models.ImageField(blank=True, upload_to="")),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="npcs",
                        to="dnd_manager.campaign",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("Common", "Common"),
                            ("Uncommon", "Uncommon"),
                            ("Rare", "Rare"),
                            ("Legendary", "Legendary"),
                        ],
                        default="Common",
                        max_length=20,
                    ),
                ),
                ("item_image", models.ImageField(blank=True, upload_to="")),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="dnd_manager.campaign",
                    ),
                ),
                (
                    "owner_character",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items_owned",
                        to="dnd_manager.character",
                    ),
                ),
                (
                    "owner_npc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items_held_by",
                        to="dnd_manager.npc",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Quest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Not Started", "Not Started"),
                            ("In Progress", "In Progress"),
                            ("Completed", "Completed"),
                        ],
                        default="Not Started",
                        max_length=20,
                    ),
                ),
                (
                    "assigned_to",
                    models.ManyToManyField(
                        blank=True, related_name="quests", to="dnd_manager.character"
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quests",
                        to="dnd_manager.campaign",
                    ),
                ),
                (
                    "related_npc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quests_given",
                        to="dnd_manager.npc",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("summary", models.TextField(blank=True)),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="dnd_manager.campaign",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdventureLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("details", models.TextField(blank=True)),
                ("xp_earned", models.PositiveIntegerField(default=0)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adventure_logs",
                        to="dnd_manager.character",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adventure_logs",
                        to="dnd_manager.session",
                    ),
                ),
            ],
        ),
    ]
