# Generated by Django 5.1.5 on 2025-04-13 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dnd_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="class_type",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="character",
            name="race",
            field=models.CharField(max_length=100),
        ),
    ]
