# Generated by Django 5.1.5 on 2025-04-14 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dnd_manager", "0002_alter_character_class_type_alter_character_race"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="name",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
