# Generated by Django 5.1.5 on 2025-04-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dnd_manager", "0003_session_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="armor_class",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="character",
            name="charisma",
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="character",
            name="constitution",
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="character",
            name="current_hit_points",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="character",
            name="dexterity",
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="character",
            name="intelligence",
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="character",
            name="max_hit_points",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="character",
            name="strength",
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="character",
            name="wisdom",
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="item",
            name="price",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
