# Generated by Django 5.1.5 on 2025-04-14 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dnd_manager", "0004_character_armor_class_character_charisma_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="item_type",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
