# Generated by Django 5.1.5 on 2025-04-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dnd_manager", "0005_item_item_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="quest",
            name="quest_type",
            field=models.CharField(
                choices=[("MAIN", "Main Quest"), ("PERSONAL", "Personal Quest")],
                default="Main",
                max_length=20,
            ),
        ),
    ]
