# Generated by Django 5.1.5 on 2025-04-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dnd_manager", "0006_quest_quest_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="quest",
            name="rewards",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
