# Generated by Django 5.1.5 on 2025-04-19 23:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dnd_manager", "0007_quest_rewards"),
    ]

    operations = [
        migrations.AddField(
            model_name="quest",
            name="start_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="quest",
            name="quest_type",
            field=models.CharField(
                choices=[
                    ("Main Quest", "Main Quest"),
                    ("Personal Quest", "Personal Quest"),
                ],
                default="Main",
                max_length=20,
            ),
        ),
    ]
