# Generated by Django 5.1.5 on 2025-04-20 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dnd_manager", "0008_quest_start_date_alter_quest_quest_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quest",
            old_name="start_date",
            new_name="quest_date",
        ),
    ]
