# Generated by Django 5.1.5 on 2025-04-20 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dnd_manager", "0009_rename_start_date_quest_quest_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("Weapon", "Weapon"),
                    ("Armor", "Armor"),
                    ("Potion", "Potion"),
                    ("Ring", "Ring"),
                    ("Rod", "Rod"),
                    ("Scroll", "Scroll"),
                    ("Staff", "Staff"),
                    ("Wand", "Wand"),
                    ("Wondrous Item", "Wondrous Item"),
                    ("Artifact", "Artifact"),
                    ("Adventuring Gear", "Adventuring Gear"),
                    ("Tool", "Tool"),
                    ("Material", "Material"),
                    ("Food/Drink", "Food/Drink"),
                    ("Miscellaneous", "Miscellaneous"),
                ],
                default="Weapon",
                max_length=30,
            ),
        ),
    ]
