# Generated by Django 5.1.5 on 2025-04-21 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dnd_manager", "0010_alter_item_item_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="adventurelog",
            name="enemies_killed",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="adventurelog",
            name="number_of_downs",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
