# Generated by Django 5.1.5 on 2025-04-24 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dnd_manager", "0013_campaign_dm"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="status",
            field=models.CharField(
                choices=[("alive", "Alive"), ("dead", "Dead"), ("retired", "Retired")],
                default="alive",
                max_length=20,
            ),
        ),
    ]
