# Generated by Django 5.1.5 on 2025-04-24 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dnd_manager", "0014_character_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="status",
            field=models.CharField(
                choices=[("Alive", "Alive"), ("Dead", "Dead"), ("Retired", "Retired")],
                default="alive",
                max_length=20,
            ),
        ),
    ]
