# Generated by Django 5.1.5 on 2025-04-24 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dnd_manager", "0015_alter_character_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Map",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("map_image", models.ImageField(blank=True, upload_to="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maps",
                        to="dnd_manager.campaign",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MapPiece",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x_pos", models.FloatField(default=0.0)),
                ("y_pos", models.FloatField(default=0.0)),
                ("label", models.CharField(blank=True, max_length=100)),
                (
                    "character",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="map_pieces",
                        to="dnd_manager.character",
                    ),
                ),
                (
                    "map_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pieces",
                        to="dnd_manager.map",
                    ),
                ),
                (
                    "npc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="map_pieces",
                        to="dnd_manager.npc",
                    ),
                ),
            ],
        ),
    ]
