# Generated by Django 5.1.5 on 2025-04-24 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dnd_manager", "0016_map_mappiece"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mappiece",
            name="map_object",
        ),
        migrations.RemoveField(
            model_name="mappiece",
            name="character",
        ),
        migrations.RemoveField(
            model_name="mappiece",
            name="npc",
        ),
        migrations.DeleteModel(
            name="Map",
        ),
        migrations.DeleteModel(
            name="MapPiece",
        ),
    ]
