# Generated by Django 5.1.5 on 2025-04-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dnd_manager",
            "0017_remove_mappiece_map_object_remove_mappiece_character_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="map_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
