# Generated by Django 5.1.5 on 2025-04-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dnd_manager", "0019_alter_character_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="main_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
