# Generated by Django 5.1.5 on 2025-03-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini_fb", "0003_image_statusimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="statusimage",
            old_name="iamge_fk",
            new_name="image_fk",
        ),
        migrations.AlterField(
            model_name="image",
            name="caption",
            field=models.TextField(blank=True),
        ),
    ]
